# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RjnmfC <- function(Xs, Xu, k, alpha, lambda, epsilon, maxiter, verbose) {
    .Call('_Rjnmf_RjnmfC', PACKAGE = 'Rjnmf', Xs, Xu, k, alpha, lambda, epsilon, maxiter, verbose)
}

RjnmfGRC <- function(Xs, Xu, A, k, alpha, beta, lambda, epsilon, maxiter, verbose) {
    .Call('_Rjnmf_RjnmfGRC', PACKAGE = 'Rjnmf', Xs, Xu, A, k, alpha, beta, lambda, epsilon, maxiter, verbose)
}

